create extension if not exists pgcrypto;

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  initial_balance numeric not null default 0,
  initial_status text,
  notes text,
  phone text,
  extra1 text,
  extra2 text,
  created_at timestamptz not null default now()
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  created_at timestamptz not null default now()
);

create table if not exists public.abouts (
  id bigint generated by default as identity primary key,
  parent text,
  description text,
  full_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  tx_date text not null,
  tx_type text not null,
  about text,
  amount numeric not null default 0,
  receiver text,
  payer text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.checks_received (
  id uuid primary key default gen_random_uuid(),
  row_no text,
  assignor text,
  bank text,
  branch text,
  doc_no text,
  account_no text,
  due_date text,
  month text,
  amount numeric not null default 0,
  sayad text,
  sayad_status text,
  status text,
  home_use text,
  receiver text,
  transferred_amount numeric not null default 0,
  transfer_status text,
  bank_box text,
  created_at timestamptz not null default now()
);

create table if not exists public.checks_outgoing (
  id uuid primary key default gen_random_uuid(),
  tx_date text,
  month text,
  amount numeric not null default 0,
  payee text,
  national_id text,
  phone text,
  sayad text,
  bank text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  national_id text,
  eitaa text,
  robika text,
  soroush text,
  bale text,
  created_at timestamptz not null default now()
);

alter table public.accounts enable row level security;
alter table public.groups enable row level security;
alter table public.abouts enable row level security;
alter table public.transactions enable row level security;
alter table public.checks_received enable row level security;
alter table public.checks_outgoing enable row level security;
alter table public.contacts enable row level security;

do $$
declare t text;
begin
  foreach t in array array['accounts','groups','abouts','transactions','checks_received','checks_outgoing','contacts'] loop
    execute format('drop policy if exists "authenticated_all_%s" on public.%I', t, t);
    execute format('create policy "authenticated_all_%s" on public.%I for all to authenticated using (true) with check (true)', t, t);
  end loop;
end $$;
