-- ============================================================
-- سامانه مدیریت مالی دادیلانه - Supabase Schema (نسخه نهایی)
-- این فایل را یک‌بار در Supabase > SQL Editor اجرا کنید.
-- ============================================================

create extension if not exists pgcrypto;

-- -------------------------
-- کاربران و پروفایل
-- -------------------------
create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role text not null default 'user' check (role in ('admin','user','viewer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -------------------------
-- اطلاعات پایه
-- -------------------------
create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  initial_balance numeric not null default 0,
  initial_status text,
  notes text,
  phone text,
  extra1 text,
  extra2 text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.abouts (
  id bigint generated by default as identity primary key,
  parent text,
  description text,
  full_name text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  national_id text,
  eitaa text,
  robika text,
  soroush text,
  bale text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -------------------------
-- تراکنش‌های مالی
-- -------------------------
create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  tx_date text not null,
  tx_type text not null,
  about text,
  amount numeric not null default 0,
  receiver text,
  payer text,
  note text,
  account_id bigint references public.accounts(id) on delete set null,
  group_id bigint references public.groups(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -------------------------
-- چک‌های دریافتی
-- -------------------------
create table if not exists public.checks_received (
  id uuid primary key default gen_random_uuid(),
  row_no text,
  assignor text,
  bank text,
  branch text,
  doc_no text,
  account_no text,
  due_date text,
  month text,
  amount numeric not null default 0,
  sayad text,
  sayad_status text,
  status text,
  home_use text,
  receiver text,
  transferred_amount numeric not null default 0,
  transfer_status text,
  bank_box text,
  account_id bigint references public.accounts(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -------------------------
-- چک‌های صادرشده
-- -------------------------
create table if not exists public.checks_outgoing (
  id uuid primary key default gen_random_uuid(),
  tx_date text,
  month text,
  amount numeric not null default 0,
  payee text,
  national_id text,
  phone text,
  sayad text,
  bank text,
  status text,
  account_id bigint references public.accounts(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -------------------------
-- تاریخچه عملیات
-- -------------------------
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  table_name text not null,
  record_id text,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

-- -------------------------
-- سازگاری با نسخه‌های قبلی
-- -------------------------
alter table public.accounts add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.accounts add column if not exists updated_at timestamptz not null default now();
alter table public.groups add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.groups add column if not exists updated_at timestamptz not null default now();
alter table public.abouts add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.abouts add column if not exists updated_at timestamptz not null default now();
alter table public.contacts add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.contacts add column if not exists updated_at timestamptz not null default now();
alter table public.transactions add column if not exists account_id bigint references public.accounts(id) on delete set null;
alter table public.transactions add column if not exists group_id bigint references public.groups(id) on delete set null;
alter table public.transactions add column if not exists contact_id bigint references public.contacts(id) on delete set null;
alter table public.transactions add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.transactions add column if not exists updated_at timestamptz not null default now();
alter table public.checks_received add column if not exists account_id bigint references public.accounts(id) on delete set null;
alter table public.checks_received add column if not exists contact_id bigint references public.contacts(id) on delete set null;
alter table public.checks_received add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.checks_received add column if not exists updated_at timestamptz not null default now();
alter table public.checks_outgoing add column if not exists account_id bigint references public.accounts(id) on delete set null;
alter table public.checks_outgoing add column if not exists contact_id bigint references public.contacts(id) on delete set null;
alter table public.checks_outgoing add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.checks_outgoing add column if not exists updated_at timestamptz not null default now();

-- -------------------------
-- ایندکس برای جستجو و فیلتر سریع
-- -------------------------
create index if not exists idx_transactions_date on public.transactions(tx_date);
create index if not exists idx_transactions_type on public.transactions(tx_type);
create index if not exists idx_transactions_account on public.transactions(account_id);
create index if not exists idx_transactions_group on public.transactions(group_id);
create index if not exists idx_received_due_date on public.checks_received(due_date);
create index if not exists idx_received_status on public.checks_received(status);
create index if not exists idx_received_sayad on public.checks_received(sayad);
create index if not exists idx_outgoing_date on public.checks_outgoing(tx_date);
create index if not exists idx_outgoing_status on public.checks_outgoing(status);
create index if not exists idx_outgoing_sayad on public.checks_outgoing(sayad);
create index if not exists idx_contacts_national_id on public.contacts(national_id);

-- -------------------------
-- تابع به‌روزرسانی updated_at
-- -------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_accounts_updated_at on public.accounts;
create trigger trg_accounts_updated_at before update on public.accounts for each row execute function public.set_updated_at();
drop trigger if exists trg_groups_updated_at on public.groups;
create trigger trg_groups_updated_at before update on public.groups for each row execute function public.set_updated_at();
drop trigger if exists trg_abouts_updated_at on public.abouts;
create trigger trg_abouts_updated_at before update on public.abouts for each row execute function public.set_updated_at();
drop trigger if exists trg_contacts_updated_at on public.contacts;
create trigger trg_contacts_updated_at before update on public.contacts for each row execute function public.set_updated_at();
drop trigger if exists trg_transactions_updated_at on public.transactions;
create trigger trg_transactions_updated_at before update on public.transactions for each row execute function public.set_updated_at();
drop trigger if exists trg_received_updated_at on public.checks_received;
create trigger trg_received_updated_at before update on public.checks_received for each row execute function public.set_updated_at();
drop trigger if exists trg_outgoing_updated_at on public.checks_outgoing;
create trigger trg_outgoing_updated_at before update on public.checks_outgoing for each row execute function public.set_updated_at();

-- -------------------------
-- ثبت خودکار تاریخچه تغییرات
-- -------------------------
create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.audit_log(user_id, table_name, record_id, action, new_data)
    values (auth.uid(), tg_table_name, new.id::text, 'INSERT', to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.audit_log(user_id, table_name, record_id, action, old_data, new_data)
    values (auth.uid(), tg_table_name, new.id::text, 'UPDATE', to_jsonb(old), to_jsonb(new));
    return new;
  else
    insert into public.audit_log(user_id, table_name, record_id, action, old_data)
    values (auth.uid(), tg_table_name, old.id::text, 'DELETE', to_jsonb(old));
    return old;
  end if;
end;
$$;

drop trigger if exists trg_accounts_audit on public.accounts;
create trigger trg_accounts_audit after insert or update or delete on public.accounts for each row execute function public.write_audit_log();
drop trigger if exists trg_groups_audit on public.groups;
create trigger trg_groups_audit after insert or update or delete on public.groups for each row execute function public.write_audit_log();
drop trigger if exists trg_abouts_audit on public.abouts;
create trigger trg_abouts_audit after insert or update or delete on public.abouts for each row execute function public.write_audit_log();
drop trigger if exists trg_contacts_audit on public.contacts;
create trigger trg_contacts_audit after insert or update or delete on public.contacts for each row execute function public.write_audit_log();
drop trigger if exists trg_transactions_audit on public.transactions;
create trigger trg_transactions_audit after insert or update or delete on public.transactions for each row execute function public.write_audit_log();
drop trigger if exists trg_received_audit on public.checks_received;
create trigger trg_received_audit after insert or update or delete on public.checks_received for each row execute function public.write_audit_log();
drop trigger if exists trg_outgoing_audit on public.checks_outgoing;
create trigger trg_outgoing_audit after insert or update or delete on public.checks_outgoing for each row execute function public.write_audit_log();

-- -------------------------
-- امنیت: فقط کاربران واردشده
-- -------------------------
alter table public.user_profiles enable row level security;
alter table public.accounts enable row level security;
alter table public.groups enable row level security;
alter table public.abouts enable row level security;
alter table public.transactions enable row level security;
alter table public.checks_received enable row level security;
alter table public.checks_outgoing enable row level security;
alter table public.contacts enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists user_profiles_select_own on public.user_profiles;
create policy user_profiles_select_own on public.user_profiles for select to authenticated using (id = auth.uid());
drop policy if exists user_profiles_insert_own on public.user_profiles;
create policy user_profiles_insert_own on public.user_profiles for insert to authenticated with check (id = auth.uid());
drop policy if exists user_profiles_update_own on public.user_profiles;
create policy user_profiles_update_own on public.user_profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- نسخه فعلی نرم‌افزار برای کاربران احراز هویت‌شده قابل استفاده است.
do $$
declare t text;
begin
  foreach t in array array['accounts','groups','abouts','transactions','checks_received','checks_outgoing','contacts'] loop
    execute format('drop policy if exists "authenticated_all_%s" on public.%I', t, t);
    execute format('create policy "authenticated_all_%s" on public.%I for all to authenticated using (true) with check (true)', t, t);
  end loop;
end $$;

drop policy if exists audit_select_authenticated on public.audit_log;
create policy audit_select_authenticated on public.audit_log for select to authenticated using (true);

-- برای درج اولین پروفایل کاربر، پس از ساخت حساب Auth می‌توانید این دستور را اجرا کنید:
-- insert into public.user_profiles (id, full_name, role) values ('USER-UUID-HERE', 'مدیر', 'admin');

-- پایان
